swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: jdwlynx.github.io
basePath: /
schemes:
  - https
paths:
  /simple-web-app:
    get:
      summary: Returns the main page
      description: This is the index.html page contents
      produces:
        - application/html
      responses:
        200:
          description: OK
